### ISSUE TITLE
incorrect $ref in management.yaml UserSchemaPropertiesProfileItem

### ISSUE THREAD

**Issue by mnahkies** [okta/okta-management-openapi-spec#180]
Instead of a `$ref` we get an object:
```
    UserSchemaPropertiesProfileItem:
      type: object
      properties:
        $ref:
          type: string
```

https://github.com/okta/okta-management-openapi-spec/blob/master/resources/3.0/management.yaml#L28283-L28287

Perhaps it is supposed to be:
 ```
    UserSchemaPropertiesProfileItem:
      type: object
      additionalProperties:
          type: string
```
